services:
  - type: web
    name: telegram-scheduler-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_PATH
        value: bot_data.db
      - key: DEFAULT_TIMEZONE
        value: UTC
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 10000